[build]
  command = "npm install && npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "22"
  NPM_FLAGS = "--no-optional"

[context.production]
  command = "npm install && npm run build"